# Mosquitto 1.6 configuration
listener 1883
allow_anonymous true

# To enable authentication, change the lines above to:
#   allow_anonymous false
#   password_file /mosquitto/config/passwd
# Then set enableAuth=True in PiotConfig.props [Mqtt.GatewayService]
